export let products = [
  {
    id: 1,
    title: "vestido Primavera",
    price: 15000,
    stock: 4,
    description: "Estanpado flores",
    category: "cortos",
    img: "https://res.cloudinary.com/dgyebngec/image/upload/v1696343520/sgv5voeeu4bxe7mr2r6q.jpg",
  },
  {
    id: 2,
    title: "vestido Azul",
    price: 14500,
    stock: 5,
    description: "coleccion Cocktail",
    category: "cortos",
    img: " https://res.cloudinary.com/dgyebngec/image/upload/v1697665128/paula-echevarria-vestido-stradivarius-corto-flores-instagram-verano-1597499949.jpg_iwnj77.jpg",
  },
  {
    id: 3,
    title: " vestido Valeria",
    price: 19000,
    stock: 2,
    description: "Largos y elegantes ",
    category: "largos",
    img: "https://res.cloudinary.com/dgyebngec/image/upload/v1697556539/ioioku49whur4qz2mx5q.jpg",
  },
  {
    id: 4,
    title: "Vestido Bohemia",
    price: 17800,
    stock: 5,
    description: "se la invitada ideal",
    category: "largos",
    img: "https://res.cloudinary.com/dgyebngec/image/upload/v1697556689/w1p3uo5gjchuhuhtbskp.jpg",
  },
];
